baseURL = 'https://python-ai-tutor.vercel.app/'
languageCode = "uk-ua"
title = "Python AI Mentor | Навчальна платформа"
theme = "book"

[markup.goldmark.renderer]
  unsafe = true

[module.hugoVersion]
  extended = true
  min = "0.158.0"

[params]
  BookLogo = "🐍"
  BookSearch = true
  BookSection = "practice"