baseURL = "https://python-ai-tutor.vercel.app/"
languageCode = "uk-ua"
title = "Python AI Mentor | Навчальна платформа"
theme = "book"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"

[params]
  BookLogo = "🐍"
  BookSearch = true
  BookSection = "practice"